#pragma once

#include "Network/NetworkComponent/NetworkHeader.h"

enum class EGamePacketHeader : uint16_t
{
	CONNECTED,
	DISCONNECT,
	SCORE_BOARD,
	SPACE_SHIP,
	OBSERVATION,
	SPAWN_PIONEER,
	DIED_PIONEER,
	INFO_OF_PIONEER_ANIMATION,
	POSSESS_PIONEER,
	INFO_OF_PIONEER_SOCKET,
	INFO_OF_PIONEER_STAT,
	INFO_OF_PROJECTILE,
	INFO_OF_RESOURCES,
	INFO_OF_BUILDING_SPAWN,
	INFO_OF_BUILDING_STAT,
	INFO_OF_BUILDING,
	DESTROY_BUILDING,
	SPAWN_ENEMY,
	INFO_OF_ENEMY_ANIMATION,
	INFO_OF_ENEMY_STAT,
	DESTROY_ENEMY
};
